### ISSUE TITLE
Fix my code!

### ISSUE THREAD

**Issue by dwhieb** [digitallinguistics/introdemo#14]
@amundo Could you do a code review of my javascript and refactor it following best practices? I'd really like to learn how I should be structuring this stuff, and I need to understand modules...

@jmangel - The code is done! Go check it out. Then check out all the awesome ways Pat is going to improve it.

**Comment by dwhieb** [comment]
@amundo gave me some sage advice, and I've incorporated some of it to improve the code in commits 73696d761307fc362b6d7e3a356957145087e2c3 and 73696d761307fc362b6d7e3a356957145087e2c3

**Comment by metasyn** [comment]
@amundo also, sort of a nuance, but @amundo once told me that git commit messages should be in the present tense. he is quite the sage !

ref [here](http://stackoverflow.com/questions/3580013/should-i-use-past-or-present-tense-in-git-commit-messages)

**Comment by dwhieb** [comment]
Huh, interesting. Good to know
