### ISSUE TITLE
Add Pat's thesis to readme

### ISSUE THREAD

**Issue by dwhieb** [digitallinguistics/introdemo#19]
@amundo Can you upload a copy of your MA and add a link to the readme? (Or not - your call.) Just following up on the idea by @metasyn to include it in our documentation.

**Comment by metasyn** [comment]
I was just thinking that it would be cool; after reading the majority of it it seems like it's pretty relevant. Plus it comes in any format you've ever wanted !

**Comment by amundo** [comment]
thanks @metasyn. i'm not super proud of it since it's kind of a mess :-/

**Comment by dwhieb** [comment]
Closes #19 ! :)
