### ISSUE TITLE
displayJSON() breaks functionality

### ISSUE THREAD

**Issue by metasyn** [digitallinguistics/introdemo#20]
So somehow during the integration of my pull request, the javascript broke:

I get an uncaught reference error on this function:
```
function displayJSON() {	
	jsonArea.innerHTML = JSON.stringify(phrase, null, 2);
};
```

![screen shot 2015-02-01 at 9 58 59 am](https://cloud.githubusercontent.com/assets/1719730/5993094/2b90a3ee-a9f9-11e4-8eab-6968c3ad3205.png)

**Comment by dwhieb** [comment]
Huh never seen that one before

**Comment by dwhieb** [comment]
Can you try in Chrome? It was working there for me

**Comment by metasyn** [comment]
The screenshot is in chrome; when I tried it a second time, I got:
```
Uncaught TypeError: Converting circular structure to JSON
demo.js:31 displayJSON
demo.js:46 render
```

**Comment by metasyn** [comment]
Found it. Line 66 of demo.js

`	phrase.translation = translationBox;`

needs to be 

` 	phrase.translation = translation;`

**Comment by dwhieb** [comment]
Sweet! Great catch :) I stupidly didn't do a comprehensive find/replace like I normally do when I changed the ids (it was 2am cut me some slack)
