### ISSUE TITLE
Add common delimiters

### ISSUE THREAD

**Issue by dwhieb** [digitallinguistics/introdemo#22]
Add all the delimiters mentioned by @metasyn in Issue #17

**Comment by dwhieb** [comment]
@metasyn I can't assign you to this issue for some reason - are you able to assign yourself?

**Comment by metasyn** [comment]
I can't do it either for some reason? No worries, I'm done with it I think.

**Comment by dwhieb** [comment]
That's so weird. It says any member can be assigned. I'll keep looking into that. I don't think it's just you either - only Pat and I show up. Might be a Owner/Dev thing.

Anyway thanks for tackling that! Can you do a pull request for it?

**Comment by dwhieb** [comment]
Figured out the assignment problem. The Dev team didn't have access to the various repos.
