### ISSUE TITLE
 contenteditable becomes uneditable in Chrome

### ISSUE THREAD

**Issue by amundo** [digitallinguistics/introdemo#26]
If you have a contenteditable element, how do you prevent that element from becoming uneditable when you delete the text inside it (in Chrome - not a problem in Firefox)

**Comment by amundo** [comment]
Relevant, perhaps:

http://stackoverflow.com/questions/3805852/select-all-text-in-contenteditable-div-when-it-focus-click

**Comment by amundo** [comment]
Maybe this is a good place to discuss `contenteditable` in general. Was the choice of `<p contenteditable>`  based on the fact that the `p` will resize as the user types?

**Comment by dwhieb** [comment]
yup, you got it. John and changed the html to use `<input>` rather than `<p>` and are seeing if we can get them reisinzg the way we want

**Comment by amundo** [comment]
POssibly relevant:

http://making.fiftythree.com/fluid-text-inputs/ 

Except that they use the React framework which is a whole nother ball of wax.

**Comment by amundo** [comment]
Sweet jeebus that approach is way too complex.

**Comment by amundo** [comment]
One thing to keep in mind is that there should only ever be one input at a time, so maybe it doesn't matter that it's fixed width.

**Comment by amundo** [comment]
We can reopen this in the future if need be.
