### ISSUE TITLE
Not clear when contenteditable elements are focused

### ISSUE THREAD

**Issue by amundo** [digitallinguistics/introdemo#27]
Focus behavior of `contenteditable` fields is made doubly tricky by the fact that there's no UX indication that the text is focused, so it's not clear that it's editable.

`:focus` and/or `:read-write` might be relevant selectors.

**Comment by amundo** [comment]
see also #26

**Comment by dwhieb** [comment]
:focus doesn't actually work for contenteditable anyway :-/

**Comment by amundo** [comment]
I think it does — you don't see a yellow background when you focus on these two elements? Works for me in FF & Chrome:

http://ruphus.com/contenteditablefocus/contenteditable.html

**Comment by dwhieb** [comment]
Last time I ran into this issue I remember not being able to use JS to give a content editable div focus. Could be wrong tho

**Comment by amundo** [comment]
Focus is a super pain to debug. Were you debugging from the console? It screws up focus like wow, because the console *has* focus. It's nuts-driving.

**Comment by dwhieb** [comment]
I can't remember actually. But yeah, so irritating.
